@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
@idUser = 81635b84-64d2-4f9a-98a8-4bb3ebb9d04f
@emailUser = lucas@gmail.com
@idCharacter = 9beeca76-6c1f-4c8a-bbcf-794c68514fc0
@gameRuleId = 461a1a7e-2efd-4068-ba55-95882002b7df
@permissionId = 5c6606cb-4d35-4b89-9f3e-556e6759da6c
@rpgGameId = 00783106-3fc0-4367-b234-6c43141768ce

### user

# @name create_account
POST {{baseUrl}}/api/accounts
Content-Type: application/json

{
    "name": "deregues",
    "email": "deregues@gmail.com",
    "password": "123456"
}

###

# @name find_user_by_email
GET {{baseUrl}}/api/accounts/{{emailUser}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name authenticate
POST {{baseUrl}}/api/sessions
Content-Type: application/json

{
    "email": "deregues@gmail.com",
    "password": "123456"
}

### character

# @name create_character
POST {{baseUrl}}/api/character
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Mãos leves",
    "race": "Carioca",
    "group": "Clérigo",
    "level": 7,
    "attributes": "8tão",
    "abilities": "Nenhuma"
}

###

# @name find_many_characters
GET {{baseUrl}}/api/character
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name find_characters_by_user
GET {{baseUrl}}/api/character/findCharacterByUser/{{idUser}}?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name find_unique_character
GET {{baseUrl}}/api/character/{{idCharacter}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_character
PUT {{baseUrl}}/api/character/{{idCharacter}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Novo Nome do Personagem",
    "race": "Nova Raça",
    "group": "Novo Grupo",
    "level": 10,
    "attributes": "Nova Força",
    "abilities": "Nova Habilidade"
}

###

# @name delete_character
DELETE {{baseUrl}}/api/character/{{idCharacter}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

### rpg-game

# @name create_rpg_game
POST {{baseUrl}}/api/rpg-game
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Nome do Jogo de RPG",
    "description": "Descrição do Jogo de RPG"
}

###

# @name find_many_rpg_games
GET {{baseUrl}}/api/rpg-game
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name find_rpg_by_user
GET {{baseUrl}}/api/rpg-game/findRpgByUser/{{idUser}}?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name find_unique_rpg_game
GET {{baseUrl}}/api/rpg-game/{{rpgGameId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_rpg_game
PUT {{baseUrl}}/api/rpg-game/{{rpgGameId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Novo Nome do Jogo de RPG",
    "description": "Nova Descrição do Jogo de RPG"
}

###

# @name delete_rpg_game
DELETE {{baseUrl}}/api/rpg-game/{{rpgGameId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

### game-rule

# @name create_game_rule
POST {{baseUrl}}/api/game-rule
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Nome da Regra",
    "description": "Descrição da Regra",
    "rpgGameId": "6958cdff-a987-436c-8c01-7361f812eb53"

}

###

# @name find_many_game_rules
GET {{baseUrl}}/api/game-rule
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name find_unique_game_rule
GET {{baseUrl}}/api/game-rule/{{gameRuleId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_game_rule
PUT {{baseUrl}}/api/game-rule/{{gameRuleId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Novo Nome da Regra",
    "description": "Nova Descrição da Regra",
    "rpgGameId": "6958cdff-a987-436c-8c01-7361f812eb53"
}

###

# @name delete_game_rule
DELETE {{baseUrl}}/api/game-rule/{{gameRuleId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

### permission

# @name create_permission
POST {{baseUrl}}/api/permission
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Nome da Permissão",
    "description": "Descrição da Permissão",
    "rpgGameId": "df573d01-c11d-4e9e-b876-9b9dd015479a"
}

###

# @name find_many_permissions
GET {{baseUrl}}/api/permission
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name find_unique_permission
GET {{baseUrl}}/api/permission/{{permissionId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

###

# @name update_permission
PUT {{baseUrl}}/api/permission/{{permissionId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Novo Nome da Permissão",
    "description": "Nova Descrição da Permissão",
    "rpgGameId": "df573d01-c11d-4e9e-b876-9b9dd015479a"
}

###

# @name delete_permission
DELETE {{baseUrl}}/api/permission/{{permissionId}}
Content-Type: application/json
Authorization: Bearer {{authToken}}