@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}

# @name create_account
POST {{baseUrl}}/api/accounts
Content-Type: application/json

{
    "name": "lucas",
    "email": "lucas@gmail.com",
    "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/api/sessions
Content-Type: application/json

{
    "email": "lucas@gmail.com",
    "password": "123456"
}

###

# @name create_character
GET {{baseUrl}}/api/character
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
   
}